import numpy as np
import pandas as pd

# Linear heating model parameters
Heat0=1.68
HeatSlope=-0.098
BaseThreshold=1.80
MeanBaseload=1.13
HeatCutoff=17.14

class BAU:
    def __init__(self):
        pass
            
    def apply(self, data):
        self.df = data
        self.setDefaults()
        self.applyHeatingLoad()
        
    def setDefaults(self):
        df = self.df
        df['rt'] = 22
        df['rtsp'] = 22
        df['exheat'] = 0 # Excess heat generated by whatever measures

    def applyHeatingLoad(self):
        df = self.df
        df['hload'] = np.maximum(0, Heat0 + HeatSlope * df.OAT )
        df['rload'] = df.hload
        df['bcons'] = df.hload + MeanBaseload
        df['cons'] = MeanBaseload # The boiler has not yet operated!
